/** The answer to a press, kept for a moment.
 *
 * One press is one intention, and the call it makes can arrive twice: a retry,
 * a renderer that asked again after a reload, a second IPC for the same button.
 * Without this the second one is a second thing — a second conversation nobody
 * pressed New for — and the person is left with two of them and no way to tell
 * which is which.
 *
 * What makes it honest is the window. Past it the press is old, the answer is
 * dropped, and a fresh press gets a fresh answer; keeping one forever would
 * hand somebody back a conversation from an hour ago. A failure is not kept
 * either: an answer worth reusing is one that happened.
 */

/** How long a press stays remembered. Long enough for a retry to land, short
 *  enough that nobody is handed yesterday's answer. */
const WINDOW = 60_000;

/** How many presses are remembered at once, so a long sitting cannot grow this
 *  without bound. */
const MOST = 64;

export class Answered<T> {
  readonly #held = new Map<string, { at: number; answer: Promise<T> }>();
  readonly #window: number;
  readonly #most: number;

  constructor(options: { window?: number; most?: number } = {}) {
    this.#window = options.window ?? WINDOW;
    this.#most = options.most ?? MOST;
  }

  /** Whether this press is still remembered. */
  get held(): number {
    return this.#held.size;
  }

  /**
   * The answer for this press, made now if it has not been answered yet.
   *
   * The key is the press's own, generated by whoever pressed: two different
   * presses carry two keys and are two answers, however alike they look.
   */
  answering(key: string, make: () => Promise<T>, at = Date.now()): Promise<T> {
    // Before the lookup, not after: a press that has gone stale must be a new
    // press, and reading the old answer first would hand it back anyway.
    this.#prune(at);
    const known = this.#held.get(key);
    if (known !== undefined) return known.answer;
    const answer = make();
    this.#held.set(key, { at, answer });
    // A refusal is not worth keeping, so the next press is a new try rather
    // than the same old answer.
    void answer.catch(() => {
      if (this.#held.get(key)?.answer === answer) this.#held.delete(key);
    });
    this.#prune(at);
    return answer;
  }

  #prune(at: number): void {
    for (const [key, one] of this.#held) {
      if (at - one.at > this.#window) this.#held.delete(key);
    }
    // Insertion order is the order they were pressed in, which is the order
    // they go stale in.
    while (this.#held.size > this.#most) {
      const oldest = this.#held.keys().next();
      if (oldest.done === true) break;
      this.#held.delete(oldest.value);
    }
  }
}
