// Draws the placeholder application icon.
//
//   node scripts/make-icon.mjs
//
// There is no artwork yet, so this generates one rather than shipping a build
// that falls back to Electron's own atom — an app called Graphe wearing
// somebody else's logo is worse than a plain shape of our own.
//
// It writes build/icon.png (1024px, transparent corners) and build/icon.icns.
// Both are committed: a packaging step that needs a browser to run is a
// packaging step that breaks on the machine that does not have one. Re-run this
// only when the mark changes, which is to say when there is real artwork.
//
// macOS conventions, since they are not obvious: the visible shape sits inside
// about 80% of the canvas with transparent margin around it, and the corner
// radius is roughly a fifth of the shape. `iconutil` does the rest.

import { chromium } from 'playwright';
import { execFile } from 'node:child_process';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

const run = promisify(execFile);
const root = fileURLToPath(new URL('..', import.meta.url));
const buildDir = join(root, 'build');
const png = join(buildDir, 'icon.png');
const icns = join(buildDir, 'icon.icns');

/** The colours are `--bg` and `--accent` from src/styles/tokens.css, dark
 *  theme. An icon is the one surface with no theme to follow, so it picks one
 *  and holds it. */
const BG = '#131312';
const ACCENT = '#e0714d';
const INK = '#f2f2ef';

/** A rising line over three points: the shape the product is named after, drawn
 *  with the same restraint as everything else. Placeholder, and honest about
 *  it — but not a letter in a circle. */
const MARK = `
<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <rect x="102" y="102" width="820" height="820" rx="184" fill="${BG}"/>
  <rect x="102" y="102" width="820" height="820" rx="184" fill="none"
        stroke="${INK}" stroke-opacity="0.10" stroke-width="4"/>
  <path d="M266 690 L432 524 L596 606 L774 372"
        fill="none" stroke="${ACCENT}" stroke-width="46"
        stroke-linecap="round" stroke-linejoin="round"/>
  <circle cx="266" cy="690" r="34" fill="${INK}"/>
  <circle cx="432" cy="524" r="34" fill="${INK}"/>
  <circle cx="596" cy="606" r="34" fill="${INK}"/>
  <circle cx="774" cy="372" r="34" fill="${INK}"/>
</svg>`;

await mkdir(buildDir, { recursive: true });

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1024, height: 1024 } });
await page.setContent(`<body style="margin:0">${MARK}</body>`);
await page.screenshot({ path: png, omitBackground: true });
await browser.close();
console.log(`wrote ${png}`);

// .icns is a bundle of sizes, and `sips` is the only thing on a Mac that will
// resample cleanly without pulling in an image library.
const iconset = join(buildDir, 'icon.iconset');
await rm(iconset, { recursive: true, force: true });
await mkdir(iconset, { recursive: true });

/** Every size macOS looks for, with its retina twin. */
const sizes = [16, 32, 64, 128, 256, 512];
for (const size of sizes) {
  await run('sips', ['-z', String(size), String(size), png, '--out', join(iconset, `icon_${size}x${size}.png`)]);
  await run('sips', [
    '-z',
    String(size * 2),
    String(size * 2),
    png,
    '--out',
    join(iconset, `icon_${size}x${size}@2x.png`),
  ]);
}

await run('iconutil', ['--convert', 'icns', '--output', icns, iconset]);
await rm(iconset, { recursive: true, force: true });
console.log(`wrote ${icns}`);

// A note beside the artwork, for whoever finds it later.
await writeFile(
  join(buildDir, 'README.md'),
  [
    '# build/',
    '',
    'Packaging resources. `icon.png` and `icon.icns` are a **placeholder**, generated by',
    '`node scripts/make-icon.mjs`. Replace both with real artwork before the first public',
    'release — a 1024×1024 PNG through the same script is the whole job.',
    '',
  ].join('\n'),
);
